name: frontend devops

on:
  push:
    branches: [ main ]
    
jobs:
  deploy:
    name: frontend test
    runs-on: ubuntu-latest
    
    steps:
    - name: get code from github
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.REMOTE_PORT }}
        script: |
          sudo rm -rf devops01
          sudo git clone https://github.com/heueun/devops01
          cd devops01
          sudo npm i
          sudo npm run build
          sudo docker build --tag heueun/frontend:latest .
          sudo docker login -u heueun -p sura8478!
          sudo docker push heueun/frontend:latest
          docker-compose -f /home/ubuntu/web.yml pull
          docker-compose -f /home/ubuntu/web.yml up --force-recreate
